### ISSUE TITLE
[Android] Keyboard overlaps Chatbot input window

### ISSUE THREAD

**Issue by robinmanuelthiel** [MikeCodesDotNET/Mobile-Cloud-Workshop#40]
![screenshot_20180412-232910](https://user-images.githubusercontent.com/5874465/38705591-53e2a3d0-3eaa-11e8-9879-8c093c8198ab.jpg)

**Comment by MikeCodesDotNET** [comment]
Closed because we're going to rebuild the bot from scratch and so this isn't an issue at the moment. 

As far as I'm aware no one has run a workshop which covers this and the bot implementation we have is pretty basic. Would rather we focused on other outstanding issues and reopen as and when the v2 of the Bot is online.

**Comment by robinmanuelthiel** [comment]
A new Bot wouldn't solve the problem, as this is based on the Web View, that we are embedding here

**Comment by robinmanuelthiel** [comment]
This might help: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.platformconfiguration.androidspecific.application.setwindowsoftinputmodeadjust?view=xamarin-forms
