### ISSUE TITLE
Mismatch between web search API parameter name and management service  API parameter name

### ISSUE THREAD

**Issue by jameslavery** [MikeCodesDotNET/Mobile-Cloud-Workshop#66]
The _search_ API expects a parameter of 'keyword':
https://github.com/MikeCodesDotNET/Mobile-Cloud-Workshop/blob/cc28a7a6ef7f31791b26795fca059d040b6059b8/Backend/Monolithic/Controllers/SearchController.cs#L30

But the Management Service API search is asking for _searchTerm_:
https://github.com/MikeCodesDotNET/Mobile-Cloud-Workshop/blob/cc28a7a6ef7f31791b26795fca059d040b6059b8/Walkthrough%20Guide/07%20API%20Management/Assets/Swagger/Search.swagger.json#L33-L48

This causes searches invoked via the Management Service to fail.

I think the Management Service search API should be changed to use _keyword_ as its parameter name. I have done this locally and it works. I can search from the Management API and from the mobile device.

**Comment by MikeCodesDotNET** [comment]
Thanks James for resolving this. I've just added some new functionality to the search API and updated the swagger doc to reflect this in 0435c656d8e6c226ce32d94fe06ea3e89d4ddd5c 

New functionality includes reverts the search functionality back to defaulting to using the search feature of Azure search rather than always using Suggestions. We now have a query parameter called "suggestions" which we can set to true if we want to enable suggestions. By default this is not enabled.
